FROM quay.io/jupyter/base-notebook:python-3.11.9

# Install from requirements.txt file
COPY --chown=${NB_UID}:${NB_GID} requirements_jupyter.txt /tmp/requirements.txt
RUN pip install --quiet --no-cache-dir --requirement /tmp/requirements.txt && \
    #jupyter labextension uninstall jupyterlab-plotly && \
    #jupyter labextension install jupyterlab-plotly@5.11.0 @jupyter-widgets/jupyterlab-manager && \
    #jupyter lab build && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

