version: '3.9'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_jupyter
      network: host
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/:/home/jovyan/notebooks/
      - ./requirements_jupyter.txt:/tmp/requirements.txt
    command: ["start.sh", "jupyter", "lab", "--ServerApp.token=''"]
  pypy:
    build:
      context: .
      dockerfile: Dockerfile_pypy
      network: host
    restart: unless-stopped
    environment:
      - FNAME=day19
    volumes:
      - ./jupyter/:/home/jovyan/notebooks/
    command: ["bash", "./use_pypy.sh"]
