FROM pypy:3.11-slim

ENV PYTHONUNBUFFERED=1

# Install from requirements.txt file
COPY --chown=${NB_UID}:${NB_GID} requirements_pypy.txt /tmp/requirements.txt
RUN pip install --quiet --no-cache-dir --requirement /tmp/requirements.txt 

WORKDIR /home/jovyan/notebooks/adventofcode2025

